// @ts-nocheck
// REMOVE ONCE TESTING IS DONE
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/FolioScene.glb -t
*/

// Run npx gltfjsx public/assets/FolioScene.glb -t when updating model (-t for TS flag)

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Room_Base: THREE.Mesh
    Table_Top: THREE.Mesh
    Table_Legs: THREE.Mesh
    Carpet: THREE.Mesh
    DeskMat: THREE.Mesh
    Monitor: THREE.Mesh
    Room_Shelves: THREE.Mesh
    Keyboard: THREE.Mesh
    Album2: THREE.Mesh
    Album1: THREE.Mesh
    Flooring: THREE.Mesh
    Windows: THREE.Mesh
    Chair: THREE.Mesh
    ArcadeCab: THREE.Mesh
    Guitar: THREE.Mesh
    PcTower: THREE.Mesh
    Boxes: THREE.Mesh
    Windowsil: THREE.Mesh
    Blinds: THREE.Mesh
    Polaroids: THREE.Mesh
    NamePlate: THREE.Mesh
    Room_Plinth: THREE.Mesh
    Mini_Body: THREE.Mesh
    Mini_Windows: THREE.Mesh
    Coffee_Cups: THREE.Mesh
    MonitorArm: THREE.Mesh
    Artstation: THREE.Mesh
    GitHub: THREE.Mesh
    LinkedIn: THREE.Mesh
    Coffee: THREE.Mesh
    Coffee_Container: THREE.Mesh
    ChilliPlant: THREE.Mesh
    Drawers: THREE.Mesh
    Headphones: THREE.Mesh
    Mouse: THREE.Mesh
    PlantPot: THREE.Mesh
    SpeakerL: THREE.Mesh
    SpeakerR: THREE.Mesh
    Vine_1: THREE.Mesh
    Vine_2: THREE.Mesh
    Vine_3: THREE.Mesh
    Vine_4: THREE.Mesh
    Vine_5: THREE.Mesh
    Games: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF("/assets/FolioScene.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Room_Base.geometry} material={nodes.Room_Base.material} position={[0, 5, 0]} />
      <mesh geometry={nodes.Table_Top.geometry} material={nodes.Table_Top.material} position={[-0.038, 0.233, -1.557]} scale={0.94} />
      <mesh geometry={nodes.Table_Legs.geometry} material={nodes.Table_Legs.material} position={[-0.038, 1.633, -3.308]} scale={0.94} />
      <mesh geometry={nodes.Carpet.geometry} material={nodes.Carpet.material} position={[0.45, 0.285, 1.567]} rotation={[0, -0.07, 0]} />
      <mesh geometry={nodes.DeskMat.geometry} material={nodes.DeskMat.material} position={[-0.038, 3.27, -2.974]} scale={0.94} />
      <mesh geometry={nodes.Monitor.geometry} material={nodes.Monitor.material} position={[-0.038, 5.013, -4.076]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.37, 1.097, 1.097]} />
      <mesh geometry={nodes.Room_Shelves.geometry} material={nodes.Room_Shelves.material} position={[0.022, 5.439, 0]} />
      <mesh geometry={nodes.Keyboard.geometry} material={nodes.Keyboard.material} position={[-0.633, 3.363, -2.918]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.02, 1, 0.936]} />
      <mesh geometry={nodes.Album2.geometry} material={nodes.Album2.material} position={[-3.663, 6.001, -4.893]} rotation={[Math.PI / 2, 0, 0]} scale={1.765} />
      <mesh geometry={nodes.Album1.geometry} material={nodes.Album1.material} position={[-2.448, 7.901, -4.893]} rotation={[Math.PI / 2, 0, 0]} scale={1.765} />
      <mesh geometry={nodes.Flooring.geometry} material={nodes.Flooring.material} scale={0.991} />
      <mesh geometry={nodes.Windows.geometry} material={nodes.Windows.material} position={[0, 5, -0.371]} />
      <mesh geometry={nodes.Chair.geometry} material={nodes.Chair.material} position={[0, 2.656, -1.212]} rotation={[-3.124, 0, Math.PI]} scale={0.9} />
      <mesh geometry={nodes.ArcadeCab.geometry} material={nodes.ArcadeCab.material} position={[-3.249, 4.11, 1.135]} rotation={[0, 0, -0.442]} scale={0.429} />
      <mesh geometry={nodes.Guitar.geometry} material={nodes.Guitar.material} position={[-3.962, 1.991, 3.462]} rotation={[2.773, -0.768, -1.833]} scale={0.812} />
      <mesh geometry={nodes.PcTower.geometry} material={nodes.PcTower.material} position={[1.965, 1.393, -1.87]} scale={[0.859, 1.03, 1.03]} />
      <mesh geometry={nodes.Boxes.geometry} material={nodes.Boxes.material} position={[-4.762, 2.605, -2.427]} rotation={[0, 0.117, 0]} scale={[0.586, 0.586, 0.777]} />
      <mesh geometry={nodes.Windowsil.geometry} material={nodes.Windowsil.material} position={[2.459, 4.348, -5.165]} />
      <mesh geometry={nodes.Blinds.geometry} material={nodes.Blinds.material} position={[2.459, 9.019, -4.776]} scale={[1.223, 1, 0.881]} />
      <mesh geometry={nodes.Polaroids.geometry} material={nodes.Polaroids.material} position={[-5.044, 8.287, 4.031]} scale={[1, 1.206, 1]} />
      <mesh geometry={nodes.NamePlate.geometry} material={nodes.NamePlate.material} position={[2.91, 4.473, -4.952]} scale={1.022} />
      <mesh geometry={nodes.Room_Plinth.geometry} material={nodes.Room_Plinth.material} position={[-0.4, -1.241, -0.4]} scale={1.109} />
      <mesh geometry={nodes.Mini_Body.geometry} material={nodes.Mini_Body.material} position={[-6.182, 7.603, -1.736]} rotation={[0, 0.436, 0]} scale={0.773} />
      <mesh geometry={nodes.Mini_Windows.geometry} material={materials.Material} position={[-6.421, 7.582, -2.312]} rotation={[0, 0.436, 0]} scale={0.773} />
      <mesh geometry={nodes.Coffee_Cups.geometry} material={nodes.Coffee_Cups.material} position={[3.376, 4.605, -3.009]} rotation={[0, 0, Math.PI / 2]} scale={1.045} />
      <mesh geometry={nodes.MonitorArm.geometry} material={nodes.MonitorArm.material} position={[-0.038, 3.265, -4.508]} scale={[0.438, 0.136, 0.438]} />
      <mesh geometry={nodes.Artstation.geometry} material={nodes.Artstation.material} position={[-5.345, 7.299, 0.412]} rotation={[Math.PI / 2, 0.175, -Math.PI / 2]} scale={0.382} />
      <mesh geometry={nodes.GitHub.geometry} material={nodes.GitHub.material} position={[-5.349, 7.298, 2.433]} rotation={[Math.PI / 2, 0.175, -Math.PI / 2]} scale={0.403} />
      <mesh geometry={nodes.LinkedIn.geometry} material={nodes.LinkedIn.material} position={[-5.347, 7.299, 1.407]} rotation={[Math.PI / 2, 0.175, -Math.PI / 2]} scale={0.403} />
      <mesh geometry={nodes.Coffee.geometry} material={nodes.Coffee.material} position={[3.67, 3.441, -3.101]} scale={1.045} />
      <mesh geometry={nodes.Coffee_Container.geometry} material={nodes.Coffee_Container.material} position={[3.995, 2.939, -3.804]} scale={[1.025, 1.119, 1.119]} />
      <mesh geometry={nodes.ChilliPlant.geometry} material={nodes.ChilliPlant.material} position={[1.583, 5.997, -5.075]} rotation={[2.007, 0.463, -2.214]} scale={0.176} />
      <mesh geometry={nodes.Drawers.geometry} material={nodes.Drawers.material} position={[3.913, 1.467, -3.666]} scale={0.957} />
      <mesh geometry={nodes.Headphones.geometry} material={nodes.Headphones.material} position={[-1.237, 5.452, -3.978]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.87, 0.87, 0.335]} />
      <mesh geometry={nodes.Mouse.geometry} material={nodes.Mouse.material} position={[1.004, 3.509, -2.87]} scale={[0.249, 0.228, 0.228]} />
      <mesh geometry={nodes.PlantPot.geometry} material={nodes.PlantPot.material} position={[-5.593, 7.932, -3.07]} rotation={[0, 0.177, 0]} scale={0.571} />
      <mesh geometry={nodes.SpeakerL.geometry} material={nodes.SpeakerL.material} position={[-2.461, 3.798, -3.679]} rotation={[Math.PI / 2, 0, -0.262]} scale={0.358} />
      <mesh geometry={nodes.SpeakerR.geometry} material={nodes.SpeakerR.material} position={[2.381, 3.798, -3.679]} rotation={[Math.PI / 2, 0, 0.262]} scale={0.358} />
      <mesh geometry={nodes.Vine_1.geometry} material={nodes.Vine_1.material} position={[-4.704, 8.345, -2.658]} rotation={[Math.PI / 2, 0, 0.229]} />
      <mesh geometry={nodes.Vine_2.geometry} material={nodes.Vine_2.material} position={[-4.758, 8.3, -3.023]} rotation={[Math.PI / 2, 0, 0.091]} />
      <mesh geometry={nodes.Vine_3.geometry} material={nodes.Vine_3.material} position={[-4.818, 8.3, -3.324]} rotation={[Math.PI / 2, 0, -0.177]} />
      <mesh geometry={nodes.Vine_4.geometry} material={nodes.Vine_4.material} position={[-4.825, 8.259, -3.56]} rotation={[Math.PI / 2, 0, -0.294]} />
      <mesh geometry={nodes.Vine_5.geometry} material={nodes.Vine_5.material} position={[-5.501, 8.376, -2.849]} rotation={[1.546, 0, 1.422]} />
      <mesh geometry={nodes.Games.geometry} material={nodes.Games.material} position={[-5.739, 4.721, -1.07]} />
    </group>
  )
}

useGLTF.preload('/FolioScene.glb')
